markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: false
rdiscount:
  extensions: [smart]

name: Hacker Within 
url: http://wackywendell.github.com/hackerwithin
description: An initial blog and site for THW at Yale
twitter: hackerwithin
github: thehackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin

